#.github/workflows/prsk-dependabot.yml
name: prsk dependabot

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  contents: read

jobs:
  rename-dependabot-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Rename dependabot PR with prsk
        uses: Narumikr/link-sekai-actions/prsk-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}